# Generated by Django 2.1.1 on 2018-09-03 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emr_core', '0002_auto_20180903_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='emr_core.Person'),
        ),
        migrations.AlterField(
            model_name='identificationdocument',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identification_documents', to='emr_core.Person'),
        ),
    ]
