# Generated by Django 2.1.1 on 2018-09-03 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emr_core', '0003_auto_20180903_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='locality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='emr_core.GeoLocation'),
            preserve_default=False,
        ),
    ]
