# Generated by Django 2.1.1 on 2018-09-03 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emr_core', '0004_address_locality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocation',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='emr_core.GeoLocation'),
        ),
    ]
